# Generated by Django 5.0.2 on 2024-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_description', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('shipment_time', models.TimeField(blank=True, null=True)),
                ('shipment_weight', models.FloatField(blank=True, null=True)),
                ('shipment_volume', models.FloatField(blank=True, null=True)),
                ('shipment_value', models.FloatField(blank=True, null=True)),
                ('shipment_cost', models.FloatField(blank=True, null=True)),
                ('shipment_origin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
