# Generated by Django 5.0.6 on 2024-06-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0002_shipment_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cargo_ready_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
