# Generated by Django 5.0.6 on 2024-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0003_shipment_cargo_ready_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_code', models.IntegerField(blank=True, null=True)),
                ('port_name', models.CharField(blank=True, max_length=30, null=True)),
                ('port_city', models.CharField(blank=True, max_length=100, null=True)),
                ('port_type', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_destination',
            field=models.ManyToManyField(to='logistify.ports'),
        ),
    ]
