# Generated by Django 5.0.6 on 2024-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0004_ports_alter_shipment_shipment_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='port_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
