# Generated by Django 5.0.6 on 2024-06-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0005_alter_ports_port_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ports',
            new_name='Port',
        ),
    ]
