# Generated by Django 5.0.6 on 2024-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0006_rename_ports_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_description', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_ready_date', models.DateField(blank=True, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('shipment_time', models.TimeField(blank=True, null=True)),
                ('shipment_weight', models.FloatField(blank=True, null=True)),
                ('shipment_volume', models.FloatField(blank=True, null=True)),
                ('shipment_value', models.FloatField(blank=True, null=True)),
                ('shipment_cost', models.FloatField(blank=True, null=True)),
                ('shipment_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_destination', models.ManyToManyField(to='logistify.port')),
            ],
        ),
    ]
