# Generated by Django 5.0.6 on 2024-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0009_alter_requestforquote_shipment_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquote',
            name='shipment_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforquote',
            name='shipment_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforquote',
            name='shipment_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestforquote',
            name='shipment_volume',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
