# Generated by Django 5.0.6 on 2024-07-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistify', '0010_requestforquote_shipment_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_state', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_id', models.CharField(blank=True, max_length=5, null=True)),
                ('uom_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='loading_bay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contacts', to='logistify.contact'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_value', models.FloatField(blank=True, null=True)),
                ('item_HSS_code', models.CharField(blank=True, max_length=15, null=True)),
                ('item_supplier_item_number', models.CharField(blank=True, max_length=30, null=True)),
                ('item_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='suppliername', to='logistify.supplier')),
                ('item_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistify.unitofmeasure')),
            ],
        ),
    ]
